const canvas=document.querySelector('#particles'); const context=canvas.getContext('2d'); const leavesLayer=document.querySelector('#leaves'); const music=document.querySelector('#background-music'); const musicButton=document.querySelector('#music-button'); const musicIcon=document.querySelector('.music-icon'); const musicLabel=document.querySelector('.music-label'); const reducedMotion=window.matchMedia('(prefers-reduced-motion: reduce)').matches; let width=0; let height=0; let devicePixelRatio=1; const particles=[];
const leafPoints=[[157,365,-26,.8],[204,326,-12,.7],[252,363,18,.9],[283,292,-18,.65],[324,335,10,.78],[205,170,-24,.75],[256,222,22,.82],[315,260,-12,.68],[374,338,14,.9],[422,394,-22,.72],[835,350,25,.82],[790,320,-14,.7],[747,364,17,.9],[809,250,-25,.72],[752,272,14,.72],[695,314,-10,.65],[778,170,20,.8],[725,220,-15,.7],[677,263,18,.7],[623,341,-18,.75],[441,237,-20,.72],[410,183,16,.75],[465,150,-7,.78],[545,237,21,.75],[588,183,-14,.78],[535,150,8,.7],[362,500,-12,.78],[300,454,19,.7],[688,460,15,.76],[745,430,-13,.8],[255,410,-28,.66],[866,391,20,.72],[400,445,8,.65],[605,440,-20,.72]];
function resizeCanvas(){devicePixelRatio=Math.min(window.devicePixelRatio||1,2); width=window.innerWidth; height=window.innerHeight; canvas.width=width*devicePixelRatio; canvas.height=height*devicePixelRatio; canvas.style.width=`${width}px`; canvas.style.height=`${height}px`; context.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);}
function random(min,max){return Math.random()*(max-min)+min;}
function createLeaves(){for(let leafIndex=0;leafIndex<500;leafIndex+=1){const [x,y,rotation,scale]=leafPoints[leafIndex%leafPoints.length]; const leafGroup=document.createElementNS('http://www.w3.org/2000/svg','g'); const leaf=document.createElementNS('http://www.w3.org/2000/svg','use'); const spread=leafIndex%5===0?18:32; const leafX=x+random(-spread,spread); const leafY=y+random(-spread,spread); const leafRotation=rotation+random(-28,28); const leafScale=scale*random(.42,.82); leafGroup.setAttribute('transform',`translate(${leafX} ${leafY})`); leaf.setAttribute('href','#leaf-shape'); leaf.setAttributeNS('http://www.w3.org/1999/xlink','xlink:href','#leaf-shape'); leaf.setAttribute('class',leafIndex%4===0?'leaf':'leaf secondary'); leaf.style.setProperty('--leaf-rotation',`${leafRotation}deg`); leaf.style.setProperty('--leaf-scale',leafScale); leaf.style.setProperty('--leaf-delay',`${14+(leafIndex%180)*.014}s`); leafGroup.appendChild(leaf); leavesLayer.appendChild(leafGroup);}}
function makeParticle(type){const isBubble=type==='bubble'; const isFallingLeaf=type==='falling-leaf'; return {type,x:random(0,width),y:random(height*.58,height+80),size:random(isFallingLeaf?4:isBubble?4:2,isFallingLeaf?10:isBubble?14:5),speed:random(isFallingLeaf?.45:.16,isFallingLeaf?1.2:type==='sparkle'?1.05:.58),drift:random(.2,1),phase:random(0,Math.PI*2),alpha:random(.35,.85),rotation:random(0,Math.PI*2)};}
function resetParticle(particle){Object.assign(particle,makeParticle(particle.type),{y:height+random(10,180)});}
function drawParticle(particle,time){const drift=Math.sin(time*.0007*particle.drift+particle.phase)*(particle.type==='heart'?11:6); const x=particle.x+drift; const y=particle.y; context.save(); context.translate(x,y); context.globalAlpha=particle.alpha*(.7+Math.sin(time*.002+particle.phase)*.3); context.strokeStyle=particle.type==='heart'?'#fff8e4':'rgba(255,245,205,.85)'; context.shadowColor='#ffe9a6'; context.shadowBlur=particle.type==='bubble'?7:10;
    if(particle.type==='bubble'){context.lineWidth=1;context.beginPath();context.arc(0,0,particle.size,0,Math.PI*2);context.stroke();context.fillStyle='rgba(255,255,255,.7)';context.fillRect(-particle.size*.35,-particle.size*.4,1.5,1.5);} if(particle.type==='sparkle'){context.lineWidth=.8;context.beginPath();context.moveTo(-particle.size*2,0);context.lineTo(particle.size*2,0);context.moveTo(0,-particle.size*2);context.lineTo(0,particle.size*2);context.stroke();} if(particle.type==='heart'){const s=particle.size;context.lineWidth=1;context.beginPath();context.moveTo(0,s);context.bezierCurveTo(-s*1.7,-s*.1,-s,-s*1.2,0,-s*.35);context.bezierCurveTo(s,-s*1.2,s*1.7,-s*.1,0,s);context.stroke();} if(particle.type==='falling-leaf'){const s=particle.size*1.35; context.rotate(particle.rotation); context.fillStyle='rgba(238,190,91,.9)'; context.shadowBlur=9; context.beginPath(); context.ellipse(0,0,s,s*.48,0,0,Math.PI*2); context.fill(); context.strokeStyle='#fff0bc'; context.lineWidth=.7; context.beginPath(); context.moveTo(-s,0); context.lineTo(s,0); context.stroke();} context.restore(); }
function animate(time=0){context.clearRect(0,0,width,height); particles.forEach((particle)=>{particle.y-=particle.speed; particle.rotation+=.01; if(particle.y<-30) resetParticle(particle); drawParticle(particle,time);}); requestAnimationFrame(animate);}
function updateMusicButton(isPlaying){musicIcon.textContent=isPlaying?'Ⅱ':'▶'; musicLabel.textContent=isPlaying?'Pause music':'Play music'; musicButton.setAttribute('aria-label',isPlaying?'Pause background music':'Play background music'); musicButton.setAttribute('aria-pressed',String(isPlaying));}
document.querySelectorAll('.photo img').forEach((image)=>{image.addEventListener('error',()=>{image.hidden=true; image.parentElement.classList.add('media-missing');});});
resizeCanvas(); createLeaves(); for(let index=0;index<72;index+=1) particles.push(makeParticle(index%3===0?'heart':index%3===1?'sparkle':'bubble')); window.addEventListener('resize',resizeCanvas);
musicButton.addEventListener('click',async()=>{if(music.paused){try{await music.play();updateMusicButton(true);}catch(error){updateMusicButton(false);console.warn('Background music could not start:',error.message);}}else{music.pause();updateMusicButton(false);}}); music.addEventListener('ended',()=>updateMusicButton(false));
if(!reducedMotion){window.setInterval(()=>{const leaf=makeParticle('falling-leaf'); leaf.y=height*random(.12,.42); leaf.x=width*random(.25,.78); particles.push(leaf);},5200);} requestAnimationFrame(animate);